### ISSUE TITLE
--stdoutを指定すると空行が1行多く出力される

### ISSUE THREAD

**Issue by naoina** [prh/prh#28]
`--stdout`オプションを指定すると、ファイルの末尾に空行がついたものが出力されます。

```console
% echo 'a line' > test.md
% cat test.md
a line
% prh --stdout --rules path/to/rules.yml test.md
a line

% 
```

出力を置き換えるタイプの自動整形ツール（Vim/Neovimで使える[ALEFix](https://github.com/w0rp/ale#2ii-fixing)など）を経由して使った場合、自動整形するたびに無限にファイル末尾に空行が追加されてしまいます。

**Comment by vvakame** [comment]
報告ありがとうございます。
修正して v5.4.1 としてリリースしました。

tsfmtの経験を踏まえてVim的な人々が必要そうなオプションは入れた気がしますが足りてなさそうだったら教えてください。

**Comment by naoina** [comment]
@vvakame ありがとうございました！
