### ISSUE TITLE
Node 4:  TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by azu** [prh/prh#30]
一応念のため報告です。
Node.js v4は`RegExp.prototype.flags`をサポートしていないため(`undefined`となる)、次の行で例外を投げてエラーとなるようです。

> TypeError: Cannot read property 'split' of undefined

https://github.com/prh/prh/blob/d6c5cf80445402bc8788a8160918940e496fb9d5/lib/utils/regexp.ts#L31

- http://node.green/#ES2015-built-in-extensions-RegExp-prototype-properties-RegExp-prototype-flags
- https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags

サポート対象が書かれてなかったので一応の報告です。

**Comment by azu** [comment]
```shell-session
✈ nodebrew exec 4 -- "node -e 'console.log(typeof RegExp.prototype.flags)'"
undefined

✈ nodebrew exec 5 -- "node -e 'console.log(typeof RegExp.prototype.flags)'"
undefined

✈ nodebrew exec 6 -- "node -e 'console.log(typeof RegExp.prototype.flags)'"
string

✈ nodebrew exec 8 -- "node -e 'console.log(typeof RegExp.prototype.flags)'"
string

```

Workaround: prhを読み込む前にpolyfillを当てることで回避できるようです。(読み込み時に評価されるらしいのでrequireする前でないとエラーがでました)

```js
/**
 * RegExp#flags polyfill
 */
if (RegExp.prototype.flags === undefined) {
    Object.defineProperty(RegExp.prototype, 'flags', {
        configurable: true,
        get: function() {
            return this.toString().match(/[gimuy]*$/)[0];
        }
    });
}

const prh = require("prh");
```

**Comment by vvakame** [comment]
報告ありがとうございます。
とりあえず最後のLTSだけサポートしておけばいいかなーという気持ちです。

**Comment by azu** [comment]
Node 4はEOLになったので閉じて良さそう。
